version: '3'

networks: 
    frontend:
        driver: ${NETWORKS_DRIVER}
    backend:
        driver: ${NETWORKS_DRIVER}
    # default:
    #     ipam:
    #         config:
    #             - subnet: 10.1.0.0/16

services:
    go-gin:
        build:
            context: ./go-gin
            dockerfile: Dockerfile
        container_name: go-gin
        ports:
            - 20201:20201
        working_dir: ${CONTAINER_WWWROOT}/mh_go
        volumes:
            - ${WWWROOT}:${CONTAINER_WWWROOT}
        networks:
            - backend
        command: ["bash", "-c", "./mh_go"]
    nginx:
        restart: always
        build: ./nginx
        container_name: nginx
        ports:
            - 80:80
            - 443:443
        volumes: 
            - ./nginx/sites:/etc/nginx/conf.d
            - ${WWWROOT}:${CONTAINER_WWWROOT}
        command: [nginx-debug, '-g', 'daemon off;']
        depends_on: 
            - php7.4-fpm
            - go-gin
        links: 
            - php7.4-fpm
            - go-gin
        networks: 
            - frontend
            - backend
    php7.4-fpm:
        build: 
            context: ./php7.4-fpm 
            args:
                - INSTALL_MONGO=${PHP_FPM_INSTALL_MONGO}
                - INSTALL_OPCACHE=${PHP_FPM_INSTALL_OPCACHE}
                - INSTALL_PHPREDIS=${PHP_FPM_INSTALL_PHPREDIS}
                - INSTALL_MYSQLI=${PHP_FPM_INSTALL_MYSQLI}
                - INSTALL_MYSQL_CLIENT=${PHP_FPM_INSTALL_MYSQL_CLIENT}
                - INSTSLL_PDO_MYSQL=${PHP_FPM_INSTSLL_PDO_MYSQL}
        container_name: php7.4-fpm
        restart: always
        working_dir: ${CONTAINER_WWWROOT}
        ports:
            - 9000:9000
        volumes: 
            - ./php7.4-fpm/php-fpm.d/www.conf:/usr/local/etc/php-fpm.d/www.conf
            - ${WWWROOT}:${CONTAINER_WWWROOT}
        networks: 
            - backend
    # jianmu-mysql:
    #     image: docker.jianmuhub.com/library/mysql:8.0.31
    #     command: --init-connect='SET NAMES utf8' --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --max-connections=1200 --max-user-connections=1000
    #     restart: always
    #     environment:
    #         MYSQL_ROOT_PASSWORD: 123456
    #         MYSQL_DATABASE: "jianmu"
    #         TZ: "Asia/Shanghai"
    #     volumes:
    #         - ./jianmu/mysql:/var/lib/mysql
            
    #     networks:
    #         - frontend
    # ci-server:
    #     image: docker.jianmuhub.com/jianmu/jianmu-server:v2.7.1
    #     restart: always
    #     environment:
    #         SPRING_PROFILES_ACTIVE: dev
    #         SPRING_DATASOURCE_URL: jdbc:mysql://jianmu-mysql:3306/jianmu?useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true
    #         SPRING_DATASOURCE_USERNAME: root
    #         SPRING_DATASOURCE_PASSWORD: 123456
    #         JIANMU_WORKER_SECRET: worker-secret
    #         JIANMU_API_ADMINPASSWD: k9kQdPd5Fw9qmD0ikMiQ
    #     #      REGISTRY_AK:
    #     #      REGISTRY_SK:
    #     volumes:
    #         - ./jianmu/data:/home/jianmu/data
    #     depends_on:
    #         - jianmu-mysql
    #     entrypoint: ["wait-for-it.sh", "jianmu-mysql:3306", "-t", "0", "--", "java", "-Duser.timezone=Asia/Shanghai",  "-jar", "jianmu-server.jar"]
        
    #     networks:
    #         - frontend
    # worker:
    #     image: docker.jianmuhub.com/jianmu/jianmu-worker-docker:v1.0.9
    #     restart: always
    #     environment:
    #         JIANMU_SRV_ADDRESS: http://ci-server:8081
    #         JIANMU_SRV_SECRET: worker-secret
    #         JIANMU_WORKER_ID: worker1
    #         # 可同时并发的容器数量，默认为2
    #         JIANMU_WORKER_CAPACITY: 5
    #     volumes:
    #         - /var/run/docker.sock:/var/run/docker.sock
    #     depends_on:
    #         - jianmu-mysql
    #         - ci-server
    #     networks:
    #         - frontend
    # web:
        # image: docker.jianmuhub.com/jianmu/jianmu-ui:v2.7.1
        # ports:
        #     - "9880:80"
        #     # - "98443:443"
        # restart: always
        # depends_on:
        #     - jianmu-mysql
        #     - ci-server
        # networks:
        #     - frontend